#' @title to read files
#' @description \code{krb.convert_percentage_vars_2015}
#' @export

krb.convert_percentage_vars_2015 <- function(sf_df){
  sf_df <- sf_df %>%
    mutate(
      # 性別割合
      krb.per.male = krb.population_male / krb.population,
      krb.per.female = krb.population_female / krb.population,
      # 年齢別人口割合
      krb.per.population0_4 = krb.population0_4 / krb.population,
      krb.per.population5_9 = krb.population5_9 / krb.population,
      krb.per.population10_14 = krb.population10_14 / krb.population,
      krb.per.population15_19 = krb.population15_19 / krb.population,
      krb.per.population20_24 = krb.population20_24 / krb.population,
      krb.per.population25_29 = krb.population25_29 / krb.population,
      krb.per.population30_34 = krb.population30_34 / krb.population,
      krb.per.population35_39 = krb.population35_39 / krb.population,
      krb.per.population40_44 = krb.population40_44 / krb.population,
      krb.per.population45_49 = krb.population45_49 / krb.population,
      krb.per.population50_54 = krb.population50_54 / krb.population,
      krb.per.population55_59 = krb.population55_59 / krb.population,
      krb.per.population60_64 = krb.population60_64 / krb.population,
      krb.per.population65_69 = krb.population65_69 / krb.population,
      krb.per.population70_74 = krb.population70_74 / krb.population,
      krb.per.population75_ = krb.population75_ / krb.population,
      # 男性年齢別人口割合
      krb.per.population_male0_4 = krb.population_male0_4 / krb.population,
      krb.per.population_male5_9 = krb.population_male5_9 / krb.population,
      krb.per.population_male10_14 = krb.population_male10_14 / krb.population,
      krb.per.population_male15_19 = krb.population_male15_19 / krb.population,
      krb.per.population_male20_24 = krb.population_male20_24 / krb.population,
      krb.per.population_male25_29 = krb.population_male25_29 / krb.population,
      krb.per.population_male30_34 = krb.population_male30_34 / krb.population,
      krb.per.population_male35_39 = krb.population_male35_39 / krb.population,
      krb.per.population_male40_44 = krb.population_male40_44 / krb.population,
      krb.per.population_male45_49 = krb.population_male45_49 / krb.population,
      krb.per.population_male50_54 = krb.population_male50_54 / krb.population,
      krb.per.population_male55_59 = krb.population_male55_59 / krb.population,
      krb.per.population_male60_64 = krb.population_male60_64 / krb.population,
      krb.per.population_male65_69 = krb.population_male65_69 / krb.population,
      krb.per.population_male70_74 = krb.population_male70_74 / krb.population,
      krb.per.population_male75_ = krb.population_male75_ / krb.population,
      # 世帯数割合
      krb.per.households1 = krb.households1 / krb.households,
      krb.per.households2 = krb.households2 / krb.households,
      krb.per.households3 = krb.households3 / krb.households,
      krb.per.households4 = krb.households4 / krb.households,
      krb.per.households5 = krb.households5 / krb.households,
      # 平均世帯人数
      krb.per.population_per_households = krb.population_per_households,
      # 種類別世帯割合
      krb.per.households_relatives = krb.households_relatives / krb.households,
      krb.per.households_core = krb.households_core / krb.households,
      krb.per.households_couple = krb.households_couple / krb.households,
      krb.per.households_couple_children = krb.households_couple_children / krb.households,
      krb.per.households_under_6 = krb.households_under_6 / krb.households,
      krb.per.households_under_18 = krb.households_under_18 / krb.households,
      krb.per.households_over_65 = krb.households_over_65 / krb.households,
      # 住宅種類別世帯割合
      krb.per.households_own = krb.households_own / krb.households,
      krb.per.households_rent = krb.households_rent / krb.households,
      # 住宅の建て方別世帯割合
      krb.per.households_detatched = krb.households_detatched / krb.households,
      krb.per.households_tenement = krb.households_tenement / krb.households,
      krb.per.households_communal_2 = krb.households_communal_2 / krb.households,
      krb.per.households_communal3_5 = krb.households_communal3_5 / krb.households,
      krb.per.households_communal6_11 = krb.households_communal6_11 / krb.households,
      krb.per.households_communal12_ = krb.households_communal12_ / krb.households,
      # 産業別人数
      krb.per.industry_A = krb.industry_A / krb.population,
      krb.per.industry_B = krb.industry_B / krb.population,
      krb.per.industry_C = krb.industry_C / krb.population,
      krb.per.industry_D = krb.industry_D / krb.population,
      krb.per.industry_E = krb.industry_E / krb.population,
      krb.per.industry_F = krb.industry_F / krb.population,
      krb.per.industry_G = krb.industry_G / krb.population,
      krb.per.industry_H = krb.industry_H / krb.population,
      krb.per.industry_I = krb.industry_I / krb.population,
      krb.per.industry_J = krb.industry_J / krb.population,
      krb.per.industry_K = krb.industry_K / krb.population,
      krb.per.industry_L = krb.industry_L / krb.population,
      krb.per.industry_M = krb.industry_M / krb.population,
      krb.per.industry_N = krb.industry_N / krb.population,
      krb.per.industry_O = krb.industry_O / krb.population,
      krb.per.industry_P = krb.industry_P / krb.population,
      krb.per.industry_Q = krb.industry_Q / krb.population,
      krb.per.industry_R = krb.industry_R / krb.population,
      krb.per.industry_S = krb.industry_S / krb.population,
      krb.per.industry_T = krb.industry_T / krb.population,
      krb.per.employer = krb.employer / krb.population,
      krb.per.self_employed = krb.self_employed / krb.population,
      krb.per.family_worker = krb.family_worker / krb.population,
      # 職業別就業者数
      krb.per.sector_A = krb.sector_A / krb.population,
      krb.per.sector_B = krb.sector_B / krb.population,
      krb.per.sector_C = krb.sector_C / krb.population,
      krb.per.sector_D = krb.sector_D / krb.population,
      krb.per.sector_E = krb.sector_E / krb.population,
      krb.per.sector_F = krb.sector_F / krb.population,
      krb.per.sector_G = krb.sector_G / krb.population,
      krb.per.sector_H = krb.sector_H / krb.population,
      krb.per.sector_I = krb.sector_I / krb.population,
      krb.per.sector_J = krb.sector_J / krb.population,
      krb.per.sector_K = krb.sector_K / krb.population,
      krb.per.sector_L = krb.sector_L / krb.population,
      # 経済構成別世帯割合
      krb.per.primary = krb.primary / krb.households,
      krb.per.primary_other = krb.primary_other / krb.households,
      krb.per.not_primary = krb.not_primary / krb.households,
      krb.per.unemployed = krb.unemployed / krb.households
    )
  }
